DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
SET search_path TO public;

CREATE TABLE Prestataires (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom varchar(100) NOT NULL,
    prenoms varchar(100) NOT NULL,
    date_naissance date NOT NULL,
    nas varchar(100) NOT NULL UNIQUE,
    note_moyenne decimal(3,2) NOT NULL DEFAULT 0 CHECK (note_moyenne BETWEEN 0 AND 5),
    courriel varchar(255) NOT NULL UNIQUE,
    telephone varchar(50) NOT NULL UNIQUE,
    adresse_numero varchar(10) NOT NULL,
    adresse_rue varchar(150) NOT NULL,
    adresse_ville varchar(100) NOT NULL,
    adresse_province varchar(100) NOT NULL,
    adresse_code_postal varchar(20) NOT NULL,
    mot_passe_hash varchar(255) NOT NULL,
    est_actif boolean NOT NULL DEFAULT TRUE,
    cree_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifier_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Clients (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom varchar(100) NOT NULL,
    prenoms varchar(100) NOT NULL,
    date_naissance date NOT NULL,
    courriel varchar(255) NOT NULL UNIQUE,
    telephone varchar(50) NOT NULL UNIQUE,
    mode_paiement varchar(100) NOT NULL,
    adresse_numero varchar(10) NOT NULL,
    adresse_rue varchar(150) NOT NULL,
    adresse_ville varchar(100) NOT NULL,
    adresse_province varchar(100) NOT NULL,
    adresse_code_postal varchar(20) NOT NULL,
    mot_passe_hash varchar(255) NOT NULL,
    est_actif boolean NOT NULL DEFAULT TRUE,
    cree_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifier_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Disponibilites (
    prestataire_id integer NOT NULL,
    jour varchar(100) NOT NULL,
    statut varchar(190) NOT NULL,
    heure_debut time NOT NULL,
    heure_fin time NOT NULL,
    CONSTRAINT pk_dispo_prestataire PRIMARY KEY (prestataire_id, jour, heure_debut, heure_fin),
    CONSTRAINT fk_dispo_prestataire_id FOREIGN KEY (prestataire_id)
        REFERENCES Prestataires(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT ck_dispo_heure CHECK (heure_debut < heure_fin)
);

CREATE TABLE Services (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom varchar(255) NOT NULL,
    prestataire_id integer NOT NULL,
    description text NOT NULL,
    duree decimal(5,2) NOT NULL CHECK (duree > 0),
    prix decimal(10,2) NOT NULL CHECK (prix > 0),
    CONSTRAINT fk_service_prestataire_id FOREIGN KEY (prestataire_id)
        REFERENCES Prestataires(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT uq_service_nom_prestataire UNIQUE (prestataire_id, nom)
);

CREATE TABLE Reservations (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id integer NOT NULL,
    prestataire_id integer NOT NULL,
    heure_debut time NOT NULL,
    heure_fin time,
    date date NOT NULL,
    statut varchar(30) NOT NULL DEFAULT 'Assignee',
    CONSTRAINT ck_reservation_statut CHECK (statut IN ('Assignee', 'En cours', 'annulee', 'Terminee')),
    CONSTRAINT fk_reservation_client_id FOREIGN KEY (client_id)
        REFERENCES Clients(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_reservation_prestataire_id FOREIGN KEY (prestataire_id)
        REFERENCES Prestataires(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Reservation_Services (
    reservation_id integer NOT NULL,
    service_id integer NOT NULL,
    prix_applique decimal(10,2) NOT NULL CHECK (prix_applique > 0),
    duree_prevue decimal(5,2) NOT NULL CHECK (duree_prevue > 0),
    quantite integer NOT NULL DEFAULT 1 CHECK (quantite >= 1),
    PRIMARY KEY (reservation_id, service_id),
    CONSTRAINT fk_rs_reservation_id FOREIGN KEY (reservation_id)
        REFERENCES Reservations(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_rs_service_id FOREIGN KEY (service_id)
        REFERENCES Services(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Commentaires (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client_id integer NOT NULL,
    reservation_id integer UNIQUE NOT NULL,
    texte text NOT NULL,
    note integer NOT NULL CHECK (note BETWEEN 1 AND 5),
    CONSTRAINT fk_comment_client_id FOREIGN KEY (client_id)
        REFERENCES Clients(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_comment_reservation_id FOREIGN KEY (reservation_id)
        REFERENCES Reservations(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Factures (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reservation_id integer NOT NULL UNIQUE,
    sous_total decimal(10,2) NOT NULL CHECK (sous_total >= 0),
    total decimal(10,2) NOT NULL CHECK (total >= 0),
    CONSTRAINT fk_facture_reservation_id FOREIGN KEY (reservation_id)
        REFERENCES Reservations(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Evenements_Outbox (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_evenement varchar(150) NOT NULL,
    type_ressource varchar(100) NOT NULL,
    ressource_id varchar(100) NOT NULL,
    cle_idempotence varchar(180) NOT NULL,
    donnees_json jsonb NOT NULL,
    statut varchar(30) NOT NULL DEFAULT 'en_attente',
    tentatives integer NOT NULL DEFAULT 0,
    derniere_erreur text,
    disponible_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    traitement_a timestamp,
    traite_a timestamp,
    cree_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifie_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_evenement_outbox_cle_idempotence UNIQUE (cle_idempotence),
    CONSTRAINT ck_evenement_outbox_statut CHECK (statut IN ('en_attente', 'en_traitement', 'traite', 'echoue')),
    CONSTRAINT ck_evenement_outbox_tentatives CHECK (tentatives >= 0)
);

CREATE INDEX idx_evenements_outbox_statut_disponible
    ON Evenements_Outbox(statut, disponible_a, id);

CREATE INDEX idx_evenements_outbox_ressource
    ON Evenements_Outbox(type_ressource, ressource_id);

CREATE TABLE Cles_Idempotence (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cle_idempotence varchar(180) NOT NULL,
    type_ressource varchar(100) NOT NULL,
    ressource_id varchar(100),
    empreinte_requete varchar(128),
    statut varchar(30) NOT NULL DEFAULT 'reservee',
    reponse_json jsonb,
    expire_a timestamp,
    traitement_a timestamp,
    traite_a timestamp,
    cree_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifie_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cle_idempotence UNIQUE (cle_idempotence),
    CONSTRAINT ck_cle_idempotence_statut CHECK (statut IN ('reservee', 'en_traitement', 'traitee', 'echouee'))
);

CREATE INDEX idx_cles_idempotence_ressource
    ON Cles_Idempotence(type_ressource, ressource_id);

CREATE INDEX idx_cles_idempotence_statut_expire
    ON Cles_Idempotence(statut, expire_a);

CREATE TABLE Journaux_Audit (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    acteur_id integer,
    role_acteur varchar(30) NOT NULL DEFAULT 'systeme',
    action varchar(150) NOT NULL,
    type_ressource varchar(100) NOT NULL,
    ressource_id varchar(100),
    resultat varchar(30) NOT NULL,
    adresse_ip varchar(45),
    correlation_id varchar(100),
    details_json jsonb,
    cree_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_journaux_audit_role CHECK (role_acteur IN ('client', 'prestataire', 'admin', 'systeme')),
    CONSTRAINT ck_journaux_audit_resultat CHECK (resultat IN ('succes', 'echec'))
);

CREATE INDEX idx_journaux_audit_ressource
    ON Journaux_Audit(type_ressource, ressource_id, cree_a);

CREATE INDEX idx_journaux_audit_acteur
    ON Journaux_Audit(role_acteur, acteur_id, cree_a);

CREATE INDEX idx_journaux_audit_correlation
    ON Journaux_Audit(correlation_id);

CREATE OR REPLACE FUNCTION calculer_total(sous_total decimal(10,2))
RETURNS decimal(10,2)
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
    RETURN ROUND(sous_total * 1.14975, 2);
END;
$$;

CREATE OR REPLACE FUNCTION definir_modifier_a()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.modifier_a = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION definir_modifie_a()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.modifie_a = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

CREATE TRIGGER clients_modifier_a_bu
BEFORE UPDATE ON Clients
FOR EACH ROW
EXECUTE FUNCTION definir_modifier_a();

CREATE TRIGGER prestataires_modifier_a_bu
BEFORE UPDATE ON Prestataires
FOR EACH ROW
EXECUTE FUNCTION definir_modifier_a();

CREATE TRIGGER evenements_outbox_modifie_a_bu
BEFORE UPDATE ON Evenements_Outbox
FOR EACH ROW
EXECUTE FUNCTION definir_modifie_a();

CREATE TRIGGER cles_idempotence_modifie_a_bu
BEFORE UPDATE ON Cles_Idempotence
FOR EACH ROW
EXECUTE FUNCTION definir_modifie_a();

CREATE OR REPLACE FUNCTION verifier_age_prestataire()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF age(CURRENT_DATE, NEW.date_naissance) < interval '18 years' THEN
        RAISE EXCEPTION 'Prestataire doit avoir au moins 18 ans';
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION verifier_age_client()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF age(CURRENT_DATE, NEW.date_naissance) < interval '16 years' THEN
        RAISE EXCEPTION 'Client doit avoir au moins 16 ans';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER verifier_age_prestataire_bi
BEFORE INSERT ON Prestataires
FOR EACH ROW
EXECUTE FUNCTION verifier_age_prestataire();

CREATE TRIGGER verifier_age_client_bi
BEFORE INSERT ON Clients
FOR EACH ROW
EXECUTE FUNCTION verifier_age_client();

CREATE OR REPLACE FUNCTION recalculer_note_moyenne_prestataire(p_prestataire_id integer)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE Prestataires p
    SET note_moyenne = COALESCE((
        SELECT ROUND(AVG(c.note), 2)
        FROM Commentaires c
        INNER JOIN Reservations r
            ON r.id = c.reservation_id
        WHERE r.prestataire_id = p_prestataire_id
    ), 0)
    WHERE p.id = p_prestataire_id;
END;
$$;

CREATE OR REPLACE FUNCTION recalculer_note_moyenne_commentaire()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_prestataire_id integer;
BEGIN
    SELECT r.prestataire_id
    INTO v_prestataire_id
    FROM Reservations r
    WHERE r.id = CASE
        WHEN TG_OP = 'DELETE' THEN OLD.reservation_id
        ELSE NEW.reservation_id
    END;

    PERFORM recalculer_note_moyenne_prestataire(v_prestataire_id);

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER commentaires_note_moyenne_aiud
AFTER INSERT OR UPDATE OR DELETE ON Commentaires
FOR EACH ROW
EXECUTE FUNCTION recalculer_note_moyenne_commentaire();

CREATE OR REPLACE FUNCTION verifier_limite_reservations_client(
    p_reservation_id integer,
    p_client_id integer,
    p_date date
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_nb integer;
BEGIN
    SELECT COUNT(*)
    INTO v_nb
    FROM Reservations r
    WHERE r.client_id = p_client_id
      AND r.date = p_date
      AND r.statut <> 'annulee'
      AND (p_reservation_id IS NULL OR r.id <> p_reservation_id);

    IF v_nb >= 2 THEN
        RAISE EXCEPTION 'Limite atteinte : un client ne peut pas avoir plus de 2 reservations le meme jour.';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION verifier_limite_reservations_client_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.statut <> 'annulee' THEN
        PERFORM verifier_limite_reservations_client(
            CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE NEW.id END,
            NEW.client_id,
            NEW.date
        );
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER verifier_limite_reservations_client_bi
BEFORE INSERT ON Reservations
FOR EACH ROW
EXECUTE FUNCTION verifier_limite_reservations_client_trigger();

CREATE TRIGGER verifier_limite_reservations_client_bu
BEFORE UPDATE ON Reservations
FOR EACH ROW
WHEN (OLD.client_id IS DISTINCT FROM NEW.client_id OR OLD.date IS DISTINCT FROM NEW.date OR OLD.statut IS DISTINCT FROM NEW.statut)
EXECUTE FUNCTION verifier_limite_reservations_client_trigger();

CREATE OR REPLACE FUNCTION verifier_chevauchement_reservation(
    p_reservation_id integer,
    p_prestataire_id integer,
    p_date date,
    p_heure_debut time,
    p_heure_fin time
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_nb integer;
BEGIN
    SELECT COUNT(*)
    INTO v_nb
    FROM Reservations r
    WHERE r.prestataire_id = p_prestataire_id
      AND r.date = p_date
      AND r.statut IN ('Assignee', 'En cours')
      AND r.id <> p_reservation_id
      AND r.heure_fin IS NOT NULL
      AND p_heure_debut < r.heure_fin
      AND p_heure_fin > r.heure_debut;

    IF v_nb > 0 THEN
        RAISE EXCEPTION 'Conflit: une autre reservation existe deja sur cette plage horaire pour ce prestataire.';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION recalculer_heure_fin_reservation(p_reservation_id integer)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_heure_debut time;
    v_heure_fin time;
    v_duree_totale decimal(10,2);
    v_prestataire_id integer;
    v_date date;
    v_statut varchar(30);
BEGIN
    SELECT r.heure_debut, r.prestataire_id, r.date, r.statut
    INTO v_heure_debut, v_prestataire_id, v_date, v_statut
    FROM Reservations r
    WHERE r.id = p_reservation_id;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    SELECT COALESCE(SUM(rs.duree_prevue * rs.quantite), 0)
    INTO v_duree_totale
    FROM Reservation_Services rs
    WHERE rs.reservation_id = p_reservation_id;

    IF v_duree_totale = 0 THEN
        v_heure_fin = v_heure_debut;
    ELSE
        v_heure_fin = v_heure_debut + (v_duree_totale::double precision * interval '1 hour');
    END IF;

    IF v_statut <> 'annulee' THEN
        PERFORM verifier_chevauchement_reservation(
            p_reservation_id,
            v_prestataire_id,
            v_date,
            v_heure_debut,
            v_heure_fin
        );
    END IF;

    UPDATE Reservations
    SET heure_fin = v_heure_fin
    WHERE id = p_reservation_id;
END;
$$;

CREATE OR REPLACE FUNCTION recalculer_facture_reservation(p_reservation_id integer)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_sous_total decimal(10,2);
BEGIN
    SELECT COALESCE(SUM(rs.prix_applique * rs.quantite), 0)
    INTO v_sous_total
    FROM Reservation_Services rs
    WHERE rs.reservation_id = p_reservation_id;

    IF v_sous_total = 0 THEN
        DELETE FROM Factures
        WHERE reservation_id = p_reservation_id;
    ELSE
        INSERT INTO Factures(reservation_id, sous_total, total)
        VALUES (p_reservation_id, v_sous_total, calculer_total(v_sous_total))
        ON CONFLICT (reservation_id)
        DO UPDATE SET
            sous_total = EXCLUDED.sous_total,
            total = EXCLUDED.total;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION reservation_services_apres_changement()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        PERFORM recalculer_heure_fin_reservation(OLD.reservation_id);
        PERFORM recalculer_facture_reservation(OLD.reservation_id);
        RETURN OLD;
    END IF;

    IF TG_OP = 'UPDATE' AND OLD.reservation_id <> NEW.reservation_id THEN
        PERFORM recalculer_heure_fin_reservation(OLD.reservation_id);
        PERFORM recalculer_facture_reservation(OLD.reservation_id);
    END IF;

    PERFORM recalculer_heure_fin_reservation(NEW.reservation_id);
    PERFORM recalculer_facture_reservation(NEW.reservation_id);
    RETURN NEW;
END;
$$;

CREATE TRIGGER reservation_services_apres_insert
AFTER INSERT ON Reservation_Services
FOR EACH ROW
EXECUTE FUNCTION reservation_services_apres_changement();

CREATE TRIGGER reservation_services_apres_update
AFTER UPDATE ON Reservation_Services
FOR EACH ROW
EXECUTE FUNCTION reservation_services_apres_changement();

CREATE TRIGGER reservation_services_apres_delete
AFTER DELETE ON Reservation_Services
FOR EACH ROW
EXECUTE FUNCTION reservation_services_apres_changement();
