CREATE TABLE IF NOT EXISTS Evenements_Outbox (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_evenement varchar(150) NOT NULL,
    type_ressource varchar(100) NOT NULL,
    ressource_id varchar(100) NOT NULL,
    cle_idempotence varchar(180) NOT NULL,
    donnees_json jsonb NOT NULL,
    statut varchar(30) NOT NULL DEFAULT 'en_attente',
    tentatives integer NOT NULL DEFAULT 0,
    derniere_erreur text,
    disponible_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    traitement_a timestamp,
    traite_a timestamp,
    cree_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifie_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_evenement_outbox_cle_idempotence UNIQUE (cle_idempotence),
    CONSTRAINT ck_evenement_outbox_statut CHECK (statut IN ('en_attente', 'en_traitement', 'traite', 'echoue')),
    CONSTRAINT ck_evenement_outbox_tentatives CHECK (tentatives >= 0)
);

CREATE INDEX IF NOT EXISTS idx_evenements_outbox_statut_disponible
    ON Evenements_Outbox(statut, disponible_a, id);

CREATE INDEX IF NOT EXISTS idx_evenements_outbox_ressource
    ON Evenements_Outbox(type_ressource, ressource_id);

CREATE TABLE IF NOT EXISTS Cles_Idempotence (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cle_idempotence varchar(180) NOT NULL,
    type_ressource varchar(100) NOT NULL,
    ressource_id varchar(100),
    empreinte_requete varchar(128),
    statut varchar(30) NOT NULL DEFAULT 'reservee',
    reponse_json jsonb,
    expire_a timestamp,
    traitement_a timestamp,
    traite_a timestamp,
    cree_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifie_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cle_idempotence UNIQUE (cle_idempotence),
    CONSTRAINT ck_cle_idempotence_statut CHECK (statut IN ('reservee', 'en_traitement', 'traitee', 'echouee'))
);

CREATE INDEX IF NOT EXISTS idx_cles_idempotence_ressource
    ON Cles_Idempotence(type_ressource, ressource_id);

CREATE INDEX IF NOT EXISTS idx_cles_idempotence_statut_expire
    ON Cles_Idempotence(statut, expire_a);

CREATE TABLE IF NOT EXISTS Journaux_Audit (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    acteur_id integer,
    role_acteur varchar(30) NOT NULL DEFAULT 'systeme',
    action varchar(150) NOT NULL,
    type_ressource varchar(100) NOT NULL,
    ressource_id varchar(100),
    resultat varchar(30) NOT NULL,
    adresse_ip varchar(45),
    correlation_id varchar(100),
    details_json jsonb,
    cree_a timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_journaux_audit_role CHECK (role_acteur IN ('client', 'prestataire', 'admin', 'systeme')),
    CONSTRAINT ck_journaux_audit_resultat CHECK (resultat IN ('succes', 'echec'))
);

CREATE INDEX IF NOT EXISTS idx_journaux_audit_ressource
    ON Journaux_Audit(type_ressource, ressource_id, cree_a);

CREATE INDEX IF NOT EXISTS idx_journaux_audit_acteur
    ON Journaux_Audit(role_acteur, acteur_id, cree_a);

CREATE INDEX IF NOT EXISTS idx_journaux_audit_correlation
    ON Journaux_Audit(correlation_id);
